[package]
name = "cargo-fel4"
version = "0.0.1"
publish = false

[dependencies]
cmake_config = { version = "*", path = "cmake_config" }
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
cargo_metadata = "0.5"
toml = "0.4"
log = "0.4"
colored = "1.6"
